const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.Platform,
		C3.Behaviors.Rotate,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.JavaScriptInEvents.Global_events_Event6,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Exps.max,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Audio.Acts.Preload,
		C3.Behaviors.Bullet.Acts.Bounce
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{Mouse: 0},
	{Touch: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{BESTSCORE: 0},
	{COINS: 0},
	{DISTANCES: 0},
	{SCORE: 0},
	{YOURSCORE: 0},
	{Sine: 0},
	{GAME: 0},
	{MENU: 0},
	{RESTART: 0},
	{SOUND: 0},
	{MOREGAMES: 0},
	{EXIT: 0},
	{FACEBOOK: 0},
	{TWITTER: 0},
	{Bullet: 0},
	{BACKGROUND: 0},
	{Fade: 0},
	{BOOM: 0},
	{Touched: 0},
	{COIN: 0},
	{ENEMY: 0},
	{STONES: 0},
	{LOGO: 0},
	{MOUSE_OFF: 0},
	{MOUSE_ON: 0},
	{Platform: 0},
	{PLAYER: 0},
	{SKELETON: 0},
	{BACKGROUND2: 0},
	{TEXT_GAME_OVER: 0},
	{TEXT_LEVEL_UP_HARD: 0},
	{TEXT_LEVEL_UP_MEDIUM: 0},
	{TEXT_READY: 0},
	{TEXT_RUN: 0},
	{GROUND: 0},
	{Rotate: 0},
	{SUNRAIN: 0},
	{Crow: 0},
	{ZOMBIES: 0},
	{Score_10: 0},
	{Score_5: 0},
	{STONESMENU: 0},
	{FRAMEBIG: 0},
	{FRAMEMEDIUM: 0},
	{FRAMESMAL: 0},
	{Sine2: 0},
	{AlienShips: 0},
	{Solid: 0},
	{COLL: 0},
	{COLL_OBJECT: 0},
	{TOUCH_SENSOR: 0},
	{TURN_LEFT: 0},
	{TURN_RIGHT: 0},
	{STOP: 0},
	{NEWSCORE: 0},
	{ALIENSHIPS: 0},
	{DESCRIPTION: 0},
	{REDIRECT_URL: 0},
	{IMAGE: 0},
	{isGameOver: 0},
	{scoreSent: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	BESTSCORE: class extends self.ISpriteFontInstance {},
	COINS: class extends self.ISpriteFontInstance {},
	DISTANCES: class extends self.ISpriteFontInstance {},
	SCORE: class extends self.ISpriteFontInstance {},
	YOURSCORE: class extends self.ISpriteFontInstance {},
	GAME: class extends self.ISpriteInstance {},
	MENU: class extends self.ISpriteInstance {},
	RESTART: class extends self.ISpriteInstance {},
	SOUND: class extends self.ISpriteInstance {},
	MOREGAMES: class extends self.ISpriteInstance {},
	EXIT: class extends self.ISpriteInstance {},
	FACEBOOK: class extends self.ISpriteInstance {},
	TWITTER: class extends self.ISpriteInstance {},
	BACKGROUND: class extends self.ITiledBackgroundInstance {},
	BOOM: class extends self.ISpriteInstance {},
	COIN: class extends self.ISpriteInstance {},
	ENEMY: class extends self.ISpriteInstance {},
	STONES: class extends self.ISpriteInstance {},
	LOGO: class extends self.ISpriteInstance {},
	MOUSE_OFF: class extends self.ISpriteInstance {},
	MOUSE_ON: class extends self.ISpriteInstance {},
	PLAYER: class extends self.ISpriteInstance {},
	SKELETON: class extends self.ISpriteInstance {},
	BACKGROUND2: class extends self.ITiledBackgroundInstance {},
	TEXT_GAME_OVER: class extends self.ISpriteInstance {},
	TEXT_LEVEL_UP_HARD: class extends self.ISpriteInstance {},
	TEXT_LEVEL_UP_MEDIUM: class extends self.ISpriteInstance {},
	TEXT_READY: class extends self.ISpriteInstance {},
	TEXT_RUN: class extends self.ISpriteInstance {},
	GROUND: class extends self.ITiledBackgroundInstance {},
	SUNRAIN: class extends self.ISpriteInstance {},
	Crow: class extends self.ISpriteInstance {},
	ZOMBIES: class extends self.ISpriteInstance {},
	Score_10: class extends self.ISpriteInstance {},
	Score_5: class extends self.ISpriteInstance {},
	STONESMENU: class extends self.ISpriteInstance {},
	FRAMEBIG: class extends self.ISpriteInstance {},
	FRAMEMEDIUM: class extends self.ISpriteInstance {},
	FRAMESMAL: class extends self.ISpriteInstance {},
	AlienShips: class extends self.ISpriteInstance {},
	COLL: class extends self.ISpriteInstance {},
	COLL_OBJECT: class extends self.ISpriteInstance {},
	TOUCH_SENSOR: class extends self.ISpriteInstance {},
	TURN_LEFT: class extends self.ISpriteInstance {},
	TURN_RIGHT: class extends self.ISpriteInstance {}
}